# Generated by Django 3.2.13 on 2022-06-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20220525_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
